<?php


DEFINE(APP_TITLE, "GREEN SCREEN");
DEFINE(APP_TITLE_DESC, "INTERACTIVO WEB");
DEFINE(APP_DESCRIPTION, "La aplicación consta en tomar una foto con un fondo verde (chroma key) para posterior cambiarle el fondo y reemplazarlo por el fondo de la activación y a su vez agregarle un marco a la foto. Una vez que se haya obtenido el resultado final de la foto se procede a subirla para que el usuario pueda compartir su experiencia en sus redes sociales.");
DEFINE(APP_HAS_IMAGES, "1");
DEFINE(APP_COUNT_IMAGES, "3");

/* Definir el número de imágenes segun el contador, por default siempre serán 3 imágenes */
DEFINE(APP_IMAGE_1, "img/preview/green.jpg");
DEFINE(APP_IMAGE_2, "img/preview/blank.png");
DEFINE(APP_IMAGE_3, "img/preview/result.png");

DEFINE(APP_A_URL, "alfa.php");

DEFINE(APP_COPYRIGHT, "&reg; ARCHER TROY S.A. DE C.V. LOS USUARIOS SE OBLIGAN A CUMPLIR CON LOS TÉRMINOS Y CONDICIONES DEL WEB. MARCA REGISTRADA. DECLARACIÓN DE PRIVACIDAD DE LA INFORMACIÓN DE MÉXICO (55) 55 39 22 72.");


/*
 * Alfa page Configuration
 */

DEFINE(ALFA_TITLE, "Nombre de la Activación");
DEFINE(ALFA_TITLE_DESC, "Registro");
?>